/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horizon.airways;

import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Ibro
 */
public class HorizonAirwaysGUI extends javax.swing.JFrame {

    /**
     * Creates new form HorizonAirwaysGUI
     */
    Connection con;
    ResultSet rs;
    Statement st;
    PreparedStatement pst;
    String tradn, tradnew, randb, fnam, lnam, statu, amo;

    public HorizonAirwaysGUI() {

        initComponents();
        this.setLocationRelativeTo(null); // to make the program appear at the center 
        this.setResizable(false); // to make the program not resizable
        rb1.setVisible(false);
        icon();
    }

    private void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("SP.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintab = new javax.swing.JPanel();
        logintab = new javax.swing.JPanel();
        cass_tab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        busmg_tab = new javax.swing.JPanel();
        gbbox = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        passbox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        reservationtab = new javax.swing.JPanel();
        resone = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        selback = new javax.swing.JButton();
        selsector = new javax.swing.JComboBox();
        seltrad = new javax.swing.JComboBox();
        selclass = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        selsub = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        infotwo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        seatpref = new javax.swing.JComboBox();
        seatzone = new javax.swing.JComboBox();
        mealpref = new javax.swing.JComboBox();
        ssr = new javax.swing.JComboBox();
        status = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        subinfo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnrtab = new javax.swing.JPanel();
        pnrfield = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        amofield = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnrrec = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        rb1 = new javax.swing.JButton();
        colamo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cancellationtab = new javax.swing.JPanel();
        canone = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        canback = new javax.swing.JButton();
        pnrveri = new javax.swing.JTextField();
        veribox = new javax.swing.JLabel();
        lday = new javax.swing.JLabel();
        bday = new javax.swing.JLabel();
        canveri = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        bcantwo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bramo = new javax.swing.JLabel();
        brtab = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        brrec = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lcantwo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lramo = new javax.swing.JLabel();
        lrtab = new javax.swing.JScrollPane();
        area3 = new javax.swing.JTextArea();
        lrrec = new javax.swing.JLabel();
        lrbut = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        repprotab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rptab = new javax.swing.JTabbedPane();
        reptab = new javax.swing.JPanel();
        reprec = new javax.swing.JScrollPane();
        area55 = new javax.swing.JTextArea();
        protab = new javax.swing.JPanel();
        prorec = new javax.swing.JScrollPane();
        area44 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(707, 424));
        setSize(new java.awt.Dimension(0, 0));

        maintab.setPreferredSize(new java.awt.Dimension(705, 424));
        maintab.setLayout(new java.awt.CardLayout());

        logintab.setMinimumSize(new java.awt.Dimension(705, 422));
        logintab.setLayout(new java.awt.CardLayout());

        cass_tab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cass_tab.setMaximumSize(new java.awt.Dimension(707, 424));
        cass_tab.setMinimumSize(new java.awt.Dimension(707, 424));
        cass_tab.setPreferredSize(new java.awt.Dimension(707, 424));
        cass_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Counter Assistant");
        cass_tab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 270, 20));

        usertxt.setBackground(new java.awt.Color(66, 92, 89));
        usertxt.setBorder(null);
        usertxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        cass_tab.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 210, 20));

        passtxt.setBackground(new java.awt.Color(66, 92, 89));
        passtxt.setBorder(null);
        passtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cass_tab.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 210, 20));

        jLabel16.setText("Login as Buisness Manager");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        cass_tab.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Login for Cancellation");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        cass_tab.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 160, 40));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Login for Reservation");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        cass_tab.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 140, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/157cc1ac2bce774c3927594057.gif"))); // NOI18N
        jLabel27.setText("jLabel27");
        cass_tab.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 280, 560));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/l.jpg"))); // NOI18N
        cass_tab.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logintab.add(cass_tab, "card2");

        busmg_tab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gbbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gbbox.setText("Back");
        gbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbboxActionPerformed(evt);
            }
        });
        busmg_tab.add(gbbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Welcome Business Manager");
        busmg_tab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 180, 30));

        userbox.setBackground(new java.awt.Color(66, 92, 89));
        userbox.setBorder(null);
        userbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userboxActionPerformed(evt);
            }
        });
        busmg_tab.add(userbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 240, 20));

        passbox.setBackground(new java.awt.Color(66, 92, 89));
        passbox.setBorder(null);
        busmg_tab.add(passbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 250, 20));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Login");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        busmg_tab.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 316, 140, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/157cc1ac2bce774c3927594057.gif"))); // NOI18N
        jLabel26.setText("jLabel26");
        busmg_tab.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 280, 560));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/bm.jpg"))); // NOI18N
        busmg_tab.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel28.setText("jLabel28");
        busmg_tab.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        logintab.add(busmg_tab, "card3");

        maintab.add(logintab, "card2");

        reservationtab.setLayout(new java.awt.CardLayout());

        resone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Make a Reservation");
        resone.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 280, 30));

        selback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selback.setText("Back");
        selback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selbackActionPerformed(evt);
            }
        });
        resone.add(selback, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 70, -1));

        selsector.setBackground(new java.awt.Color(0, 0, 0));
        selsector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selsector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Sector", "Chicago to New-York", "Memphis to New-York", "Miami to New-York", "New-Orleans to New-York", "New-York to Chicago", "New-York to Memphis", "New-York to Miami", "New-York to New-Orleans", "New-York to Pittsburgh", "Pittsburgh to New-York", "" }));
        selsector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selsector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selsectorActionPerformed(evt);
            }
        });
        resone.add(selsector, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 180, 40));

        seltrad.setBackground(new java.awt.Color(0, 0, 0));
        seltrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seltrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Travel Date" }));
        seltrad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seltrad.setEnabled(false);
        seltrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seltradActionPerformed(evt);
            }
        });
        resone.add(seltrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 220, 40));

        selclass.setBackground(new java.awt.Color(0, 0, 0));
        selclass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Class" }));
        selclass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selclass.setEnabled(false);
        selclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selclassActionPerformed(evt);
            }
        });
        resone.add(selclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 170, 40));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cancel");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        resone.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 150, 20));

        selsub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selsub.setText("Submit");
        selsub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selsub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selsubMouseClicked(evt);
            }
        });
        resone.add(selsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 160, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/res1 n 2n.jpg"))); // NOI18N
        resone.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        reservationtab.add(resone, "card2");

        infotwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infotwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Customer Details");
        infotwo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 30));

        fname.setBackground(new java.awt.Color(66, 92, 89));
        fname.setBorder(null);
        infotwo.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, 30));

        lname.setBackground(new java.awt.Color(66, 92, 89));
        lname.setBorder(null);
        infotwo.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 150, 30));

        age.setBackground(new java.awt.Color(66, 92, 89));
        age.setBorder(null);
        infotwo.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 30, 30));

        gender.setBackground(new java.awt.Color(0, 0, 0));
        gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "M", "F" }));
        infotwo.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, 40));

        seatpref.setBackground(new java.awt.Color(0, 0, 0));
        seatpref.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seatpref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seat Pref", "Aisle", "Window" }));
        infotwo.add(seatpref, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 200, 40));

        seatzone.setBackground(new java.awt.Color(0, 0, 0));
        seatzone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        seatzone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seat Zone", "Smoking", "Non-Smoking" }));
        infotwo.add(seatzone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 200, 40));

        mealpref.setBackground(new java.awt.Color(0, 0, 0));
        mealpref.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mealpref.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meal Pref", "Vegeterian", "Non-Vegeterian" }));
        infotwo.add(mealpref, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 200, 40));

        ssr.setBackground(new java.awt.Color(0, 0, 0));
        ssr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ssr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSR", "Heart", "Body", "Other" }));
        infotwo.add(ssr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 40));

        status.setBackground(new java.awt.Color(0, 0, 0));
        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Status", "Confirmed", "Over-Booked", "Wait-Listed" }));
        infotwo.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 200, 40));

        jLabel9.setText("Firstname:");
        infotwo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel10.setText("Age:");
        infotwo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel12.setText("Lastname:");
        infotwo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        subinfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subinfo.setText("Submit");
        subinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subinfoMouseClicked(evt);
            }
        });
        infotwo.add(subinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 160, 30));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Cancel");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        infotwo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 150, 30));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/res1 n 2.jpg"))); // NOI18N
        infotwo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        reservationtab.add(infotwo, "card3");

        pnrtab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnrtab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnrfield.setEditable(false);
        pnrfield.setBackground(new java.awt.Color(66, 92, 89));
        pnrfield.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pnrfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnrfield.setBorder(null);
        pnrfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnrfieldActionPerformed(evt);
            }
        });
        pnrtab.add(pnrfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 250, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Print");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        pnrtab.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, 30));

        amofield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amofield.setText("0.00");
        amofield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnrtab.add(amofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 111, 350, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Customer PNR");
        pnrtab.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 40));

        area1.setEditable(false);
        area1.setColumns(20);
        area1.setRows(5);
        pnrrec.setViewportView(area1);

        pnrtab.add(pnrrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 200));

        rb1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rb1.setText("Back");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        pnrtab.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 80, 30));

        colamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colamo.setText("Collected");
        colamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colamoMouseClicked(evt);
            }
        });
        pnrtab.add(colamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 130, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/prnt.jpg"))); // NOI18N
        pnrtab.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        reservationtab.add(pnrtab, "card4");

        maintab.add(reservationtab, "card3");

        cancellationtab.setLayout(new java.awt.CardLayout());

        canone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cancel a Reservation");
        canone.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 280, 40));

        canback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        canback.setText("Back");
        canback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbackActionPerformed(evt);
            }
        });
        canone.add(canback, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 60, 30));

        pnrveri.setBackground(new java.awt.Color(66, 92, 89));
        pnrveri.setBorder(null);
        canone.add(pnrveri, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 340, 40));

        veribox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        veribox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        veribox.setText("Undefined");
        canone.add(veribox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 300, 30));

        lday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lday.setText("Less than a Day");
        lday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldayMouseClicked(evt);
            }
        });
        canone.add(lday, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 360, 150, 30));

        bday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bday.setText("Before a Day");
        bday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bdayMouseClicked(evt);
            }
        });
        canone.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 150, 30));

        canveri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canveri.setText("Verify");
        canveri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canveriMouseClicked(evt);
            }
        });
        canone.add(canveri, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 150, 120, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/canc1.jpg"))); // NOI18N
        canone.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cancellationtab.add(canone, "card2");

        bcantwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Refund Tab");
        bcantwo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 250, 30));

        bramo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        bramo.setText("0.00");
        bcantwo.add(bramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 380, 50));

        area2.setColumns(20);
        area2.setRows(5);
        brtab.setViewportView(area2);

        bcantwo.add(brtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 670, 190));

        brrec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brrec.setText("Print Receipt");
        brrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brrecMouseClicked(evt);
            }
        });
        bcantwo.add(brrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 30));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Refund");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        bcantwo.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 130, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/becan 1 2.jpg"))); // NOI18N
        bcantwo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 710, -1));

        cancellationtab.add(bcantwo, "card3");

        lcantwo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Refund Tab");
        lcantwo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 250, 30));

        lramo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        lramo.setText("0.00");
        lcantwo.add(lramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 350, 30));

        area3.setColumns(20);
        area3.setRows(5);
        lrtab.setViewportView(area3);

        lcantwo.add(lrtab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 210));

        lrrec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lrrec.setText("Print Receipt");
        lrrec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lrrec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrrecMouseClicked(evt);
            }
        });
        lcantwo.add(lrrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, 30));

        lrbut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lrbut.setText("Refund");
        lrbut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lrbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrbutMouseClicked(evt);
            }
        });
        lcantwo.add(lrbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 130, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/becan 1 2.jpg"))); // NOI18N
        lcantwo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cancellationtab.add(lcantwo, "card3");

        maintab.add(cancellationtab, "card4");

        repprotab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reports and Processing Tab");
        repprotab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 387, 70));

        area55.setColumns(20);
        area55.setRows(5);
        reprec.setViewportView(area55);

        javax.swing.GroupLayout reptabLayout = new javax.swing.GroupLayout(reptab);
        reptab.setLayout(reptabLayout);
        reptabLayout.setHorizontalGroup(
            reptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reptabLayout.createSequentialGroup()
                .addComponent(reprec, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        reptabLayout.setVerticalGroup(
            reptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reptabLayout.createSequentialGroup()
                .addComponent(reprec, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        rptab.addTab("Daily Collection Tab", reptab);

        area44.setColumns(20);
        area44.setRows(5);
        prorec.setViewportView(area44);

        javax.swing.GroupLayout protabLayout = new javax.swing.GroupLayout(protab);
        protab.setLayout(protabLayout);
        protabLayout.setHorizontalGroup(
            protabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prorec, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        protabLayout.setVerticalGroup(
            protabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prorec, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        rptab.addTab("Scheduled Flight Tab", protab);

        repprotab.add(rptab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizon/airways/report.jpg"))); // NOI18N
        repprotab.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        maintab.add(repprotab, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void userboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userboxActionPerformed

    private void gbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbboxActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(cass_tab);
        maintab.repaint();
        maintab.revalidate(); // TODO add your handling code here:
    }//GEN-LAST:event_gbboxActionPerformed

    private void selbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selbackActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(cass_tab);
        maintab.repaint();
        maintab.revalidate();    // TODO add your handling code here:
    }//GEN-LAST:event_selbackActionPerformed

    private void canbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbackActionPerformed
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(logintab);
        maintab.repaint();
        maintab.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_canbackActionPerformed

    private void selsectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selsectorActionPerformed
        if (selsector.getSelectedItem().equals("Chicago to New-York")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-04");
            seltrad.addItem("2020-03-07");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("Memphis to New-York")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-03");
            seltrad.addItem("2020-03-06");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("Miami to New-York")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-03");
            seltrad.addItem("2020-03-13");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-Orleans to New-York")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-02");
            seltrad.addItem("2020-03-05");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-York to Chicago")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-11");
            seltrad.addItem("2020-03-14");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-York to Memphis")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-01");
            seltrad.addItem("2020-03-10");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-York to Miami")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-10");
            seltrad.addItem("2020-03-13");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-York to New-Orleans")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-02");
            seltrad.addItem("2020-03-05");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("New-York to Pittsburgh")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-09");
            seltrad.addItem("2020-03-12");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else if (selsector.getSelectedItem().equals("Pittsburgh to New-York")) {
            seltrad.removeAllItems();
            seltrad.addItem("Choose a Travel Date");
            seltrad.addItem("2020-03-09");
            seltrad.addItem("2020-03-12");
            seltrad.setEnabled(true);
            selclass.removeAllItems();
            selclass.addItem("Choose a Class");
            selclass.addItem("First Class");
            selclass.addItem("Business Class");
            selclass.addItem("Economy Class");
            selclass.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Choose a Valid Sector :(");
        }
    }//GEN-LAST:event_selsectorActionPerformed

    private void seltradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seltradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seltradActionPerformed

    private void pnrfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnrfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnrfieldActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(resone);
        maintab.repaint();
        maintab.revalidate();
    }//GEN-LAST:event_rb1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select * from Users where UserName=? and Password=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, usertxt.getText());
            pst.setString(2, passtxt.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(reservationtab);
                maintab.repaint();
                maintab.revalidate();
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password not Correct");
                usertxt.setText("");
                passtxt.setText("");
            }
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select * from Users where UserName=? and Password=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, usertxt.getText());
            pst.setString(2, passtxt.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(cancellationtab);
                maintab.repaint();
                maintab.revalidate();
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password not Correct");
                usertxt.setText("");
                passtxt.setText("");
            }
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        maintab.removeAll();
        maintab.validate();
        maintab.repaint();
        maintab.add(busmg_tab);
        maintab.repaint();
        maintab.revalidate();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select * from Users where UserName=? and Password=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, userbox.getText());
            pst.setString(2, passbox.getText());
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Username and Password Matched");
                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(repprotab);
                maintab.repaint();
                maintab.revalidate();
            } else {
                JOptionPane.showMessageDialog(null, "Username and Password not Correct");
                usertxt.setText("");
                passtxt.setText("");
            }
            con.close();

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqll = "select * from ScheduledFlights;";
            st = con.createStatement();
            rs = st.executeQuery(sqll);

            String Userdata = "";

            while (rs.next()) {
                Userdata = rs.getString(1) + "      " + rs.getDate(2) + "       " + rs.getTime(3) + "       " + rs.getInt(4) + "        " + rs.getInt(5) + "        " + rs.getInt(6) + "\n";
                area44.setText(Userdata);
            }
            st.close();
            con.close();

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqla = "select * from DailyCollection;";
            st = con.createStatement();
            rs = st.executeQuery(sqla);

            String Userdat = "";

            while (rs.next()) {
                Userdat = rs.getString(1) + "       " + rs.getDate(2) + "       " + rs.getString(3) + "     " + rs.getInt(4) + "\n";
                area55.setText(Userdat);
            }
            st.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void selclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selclassActionPerformed

    private void selsubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selsubMouseClicked
        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select FlightNo from Flights where FlightDate = ?;";
            pst = con.prepareStatement(sql);
            String trad = seltrad.getSelectedItem().toString();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = sdf1.parse(trad);
            java.sql.Date sqltrad = new java.sql.Date(date.getTime());
            tradnew = sqltrad.toString();
            pst.setString(1, tradnew);
            rs = pst.executeQuery();
            rs.next();
            tradn = rs.getString("FlightNo");
            pst.close();
            con.close();
            System.out.println(tradnew);
            System.out.println(tradn);

            if (selclass.getSelectedItem().equals("First Class")) {
                con = HorizonAirways.getConnection();
                String sqll = "select FirstClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("FirstClassSeatsAvailable");

                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;

                pst.close();
                con.close();

                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);

                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set FirstClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");

                pst.close();
                con.close();

                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(infotwo);
                maintab.repaint();
                maintab.revalidate();
            } else if (selclass.getSelectedItem().equals("Business Class")) {
                con = HorizonAirways.getConnection();
                String sqll = "select BusinessClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("BusinessClassSeatsAvailable");

                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;

                pst.close();
                con.close();

                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);

                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set BusinessClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");

                pst.close();
                con.close();

                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(infotwo);
                maintab.repaint();
                maintab.revalidate();
            } else if (selclass.getSelectedItem().equals("Economy Class")) {
                con = HorizonAirways.getConnection();
                String sqll = "select EconomyClassSeatsAvailable from ScheduledFlights where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqll);
                pst.setString(1, tradn);
                pst.setString(2, tradnew);
                rs = pst.executeQuery();
                rs.next();
                String cls = rs.getString("EconomyClassSeatsAvailable");

                int clsa = Integer.parseInt(cls);
                int clsb = clsa - 1;

                pst.close();
                con.close();

                System.out.println(cls);
                System.out.println(clsa);
                System.out.println(clsb);

                con = HorizonAirways.getConnection();
                String sqlll = "update ScheduledFlights set EconomyClassSeatsAvailable=? where FlightNo=? and FlightDate=?;";
                pst = con.prepareStatement(sqlll);
                pst.setInt(1, clsb);
                pst.setString(2, tradn);
                pst.setString(3, tradnew);
                pst.executeUpdate(); //this
                JOptionPane.showMessageDialog(this, "Update Sucessful :)");

                pst.close();
                con.close();

                maintab.removeAll();
                maintab.validate();
                maintab.repaint();
                maintab.add(infotwo);
                maintab.repaint();
                maintab.revalidate();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Details Selected :(");
            }
            pst.close();
            con.close();

        } catch (ClassNotFoundException | ParseException | SQLException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void selcanActionPerformed(java.awt.event.ActionEvent evt) {
        seltrad.removeAllItems();
        seltrad.addItem("Choose a Travel Date");
        seltrad.setEnabled(false);
        selclass.removeAllItems();
        selclass.addItem("Choose a Class");
        selclass.setEnabled(false);
    }

    private void subinfoActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            con = HorizonAirways.getConnection();

            Random rand = new Random();
            int randa = rand.nextInt(100000000);
            randb = Integer.toString(randa);
            String travno = tradn;
            String travda = tradnew;
            fnam = fname.getText();
            lnam = lname.getText();
            String agea = age.getText();
            int ageb = Integer.parseInt(agea);
            String gende = gender.getSelectedItem().toString();
            String clas = selclass.getSelectedItem().toString();
            String seatpre = seatpref.getSelectedItem().toString();
            String seatzon = seatzone.getSelectedItem().toString();
            String mealpre = mealpref.getSelectedItem().toString();
            String ssra = ssr.getSelectedItem().toString();
            statu = status.getSelectedItem().toString();

            System.out.println(randb);
            System.out.println(travno);
            System.out.println(travda);
            System.out.println(fnam);
            System.out.println(lnam);
            System.out.println(ageb);
            System.out.println(gende);
            System.out.println(clas);
            System.out.println(seatpre);
            System.out.println(seatzon);
            System.out.println(mealpre);
            System.out.println(ssra);
            System.out.println(statu);

            String sqlaba = "insert into Passenger values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";

            pst = con.prepareStatement(sqlaba);
            pst.setString(1, randb);
            pst.setString(2, travno);
            pst.setString(3, travda);
            pst.setString(4, fnam);
            pst.setString(5, lnam);
            pst.setInt(6, ageb);
            pst.setString(7, gende);
            pst.setString(8, clas);
            pst.setString(9, seatpre);
            pst.setString(10, seatzon);
            pst.setString(11, mealpre);
            pst.setString(12, ssra);
            pst.setString(13, statu);
            pst.setString(14, "N");

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Passenger Details has been Uploaded :)");

            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(pnrtab);
            maintab.repaint();
            maintab.revalidate();

            pnrfield.setText(randb);

            price();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_selsubMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        seltrad.removeAllItems();
        seltrad.addItem("Choose a Travel Date");
        seltrad.setEnabled(false);
        selclass.removeAllItems();
        selclass.addItem("Choose a Class");
        selclass.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void subinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subinfoMouseClicked
        try {
            con = HorizonAirways.getConnection();

            Random rand = new Random();
            int randa = rand.nextInt(100000000);
            randb = Integer.toString(randa);
            String travno = tradn;
            String travda = tradnew;
            fnam = fname.getText();
            lnam = lname.getText();
            String agea = age.getText();
            int ageb = Integer.parseInt(agea);
            String gende = gender.getSelectedItem().toString();
            String clas = selclass.getSelectedItem().toString();
            String seatpre = seatpref.getSelectedItem().toString();
            String seatzon = seatzone.getSelectedItem().toString();
            String mealpre = mealpref.getSelectedItem().toString();
            String ssra = ssr.getSelectedItem().toString();
            statu = status.getSelectedItem().toString();

            System.out.println(randb);
            System.out.println(travno);
            System.out.println(travda);
            System.out.println(fnam);
            System.out.println(lnam);
            System.out.println(ageb);
            System.out.println(gende);
            System.out.println(clas);
            System.out.println(seatpre);
            System.out.println(seatzon);
            System.out.println(mealpre);
            System.out.println(ssra);
            System.out.println(statu);

            String sqlaba = "insert into Passenger values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";

            pst = con.prepareStatement(sqlaba);
            pst.setString(1, randb);
            pst.setString(2, travno);
            pst.setString(3, travda);
            pst.setString(4, fnam);
            pst.setString(5, lnam);
            pst.setInt(6, ageb);
            pst.setString(7, gende);
            pst.setString(8, clas);
            pst.setString(9, seatpre);
            pst.setString(10, seatzon);
            pst.setString(11, mealpre);
            pst.setString(12, ssra);
            pst.setString(13, statu);
            pst.setString(14, "N");

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Passenger Details has been Uploaded :)");

            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(pnrtab);
            maintab.repaint();
            maintab.revalidate();

            pnrfield.setText(randb);

            price();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_subinfoMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        fname.setText("");
        lname.setText("");
        age.setText("");
        gender.setSelectedItem("Gender");
        mealpref.setSelectedItem("Meal Pref");
        seatzone.setSelectedItem("Seat Zone");
        seatpref.setSelectedItem("Seat Pref");
        ssr.setSelectedItem("SSR");
        status.setSelectedItem("Status");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void lrrecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrrecMouseClicked
        try {
            area3.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lrrecMouseClicked

    private void lrbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrbutMouseClicked
        String pnr = pnrveri.getText();

        area3.setText("******************************************************************************************************************************************" + "\n");
        area3.setText(area3.getText() + "                                                                       Horizon Airways" + "\n");
        area3.setText(area3.getText() + "                                                                       Passenger Details" + "\n");
        area3.setText(area3.getText() + "******************************************************************************************************************************************" + "\n\n");
        area3.setText(area3.getText() + "PNR Number: " + pnr + "\n\n");
        area3.setText(area3.getText() + "Refunded Amount: " + lramo.getText() + "\n\n");
        area3.setText(area3.getText() + "                                                                                                                                                       Signature: ");
    }//GEN-LAST:event_lrbutMouseClicked

    private void bdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdayMouseClicked
        try {
            // TODO add your handling code here:
            String pnr = pnrveri.getText();

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select Amount from DailyCollection where PnrNo=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, pnr);
            rs = pst.executeQuery();
            rs.next();
            String pric = rs.getString("Amount");
            pst.close();
            con.close();

            bramo.setText(pric);

            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(bcantwo);
            maintab.repaint();
            maintab.revalidate();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bdayMouseClicked

    private void ldayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldayMouseClicked
        try {
            // TODO add your handling code here:
            String pnr = pnrveri.getText();

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select Amount from DailyCollection where PnrNo=?;";
            pst = con.prepareStatement(sql);
            pst.setString(1, pnr);
            rs = pst.executeQuery();
            rs.next();
            String pric = rs.getString("Amount");
            pst.close();
            con.close();

            double qwe, qwer, qwert;
            qwe = Double.parseDouble(pric);
            qwer = qwe / 10;
            qwert = qwe - qwer;
            String pricc = Double.toString(qwert);
            lramo.setText(pricc);

            maintab.removeAll();
            maintab.validate();
            maintab.repaint();
            maintab.add(lcantwo);
            maintab.repaint();
            maintab.revalidate();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_ldayMouseClicked

    private void canveriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canveriMouseClicked
        String pnr = pnrveri.getText();

        try {
            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sql = "select PnrNo from Passenger where PnrNo=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, pnr);
            rs = pst.executeQuery();

            if (rs.next()) {
                veribox.setText("Verified :)");
                canveri.setEnabled(true);
                lday.setEnabled(true);
            } else {
                veribox.setText("Not Verified :(");
            }
            pst.close();
            con.close();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_canveriMouseClicked

    private void colamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colamoMouseClicked
        try {
            // TODO add your handling code here:

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqlllll = "select DepTime from Flights where FlightNo=? and FlightDate=?;";
            pst = con.prepareStatement(sqlllll);
            pst.setString(1, tradn);
            pst.setString(2, tradnew);
            rs = pst.executeQuery();
            rs.next();
            String dept = rs.getString("DepTime");
            pst.close();
            con.close();

            con = HorizonAirways.getConnection(); // to call the methode i created in the former cli document
            String sqllll = "select ArrTime from Flights where FlightNo=? and FlightDate=?;";
            pst = con.prepareStatement(sqllll);
            pst.setString(1, tradn);
            pst.setString(2, tradnew);
            rs = pst.executeQuery();
            rs.next();
            String arrt = rs.getString("ArrTime");
            pst.close();
            con.close();

            con = HorizonAirways.getConnection(); // this
            String sqrl = "insert into DailyCollection values (?,?,?,?);";
            pst = con.prepareStatement(sqrl);
            pst.setString(1, randb);
            pst.setString(2, java.time.LocalDateTime.now().toString()); //this
            pst.setString(3, "C");
            Double amoo = Double.parseDouble(amo);
            pst.setDouble(4, amoo);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Daily Collection File Updated :)");
            pst.close();
            con.close();

            area1.setText("******************************************************************************************************************************************" + "\n");
            area1.setText(area1.getText() + "                                                                       Horizon Airways" + "\n");
            area1.setText(area1.getText() + "                                                                       Passenger Details" + "\n");
            area1.setText(area1.getText() + "******************************************************************************************************************************************" + "\n\n");
            area1.setText(area1.getText() + "                                                                                                                                                       Date of issue: " + java.time.LocalDate.now() + "\n\n\n\n");
            area1.setText(area1.getText() + "NOT TRANSFERABLE" + "\n\n");
            area1.setText(area1.getText() + "Passenger Name: " + fnam + "   " + lnam + "\n\n");
            area1.setText(area1.getText() + "Sector: " + (String) selsector.getSelectedItem() + "\n\n");
            area1.setText(area1.getText() + "Flight: " + tradn + "      Class: " + (String) selclass.getSelectedItem() + "      Date: " + tradnew + "       Dep. Time: " + dept + "     Arr. Time: " + arrt + "     Status: " + statu + "\n\n");
            area1.setText(area1.getText() + "                                                                                                                                                       Signature: ");

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        rb1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_colamoMouseClicked

    private void brrecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brrecMouseClicked
        try {
            // TODO add your handling code here:
            area2.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brrecMouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
 String pnr = pnrveri.getText();

        area2.setText("******************************************************************************************************************************************" + "\n");
        area2.setText(area2.getText() + "                                                                       Horizon Airways" + "\n");
        area2.setText(area2.getText() + "                                                                       Passenger Details" + "\n");
        area2.setText(area2.getText() + "******************************************************************************************************************************************" + "\n\n");
        area2.setText(area2.getText() + "PNR Number: " + pnr + "\n\n");
        area2.setText(area2.getText() + "Refunded Amount: " + bramo.getText() + "\n\n");
        area2.setText(area2.getText() + "                                                                                                                                                       Signature: ");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        try {        
            area1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel32MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorizonAirwaysGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Thread.sleep(3000);
                } catch (Exception e) {

                }

                new HorizonAirwaysGUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel amofield;
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JTextArea area3;
    private javax.swing.JTextArea area44;
    private javax.swing.JTextArea area55;
    private javax.swing.JPanel bcantwo;
    private javax.swing.JLabel bday;
    private javax.swing.JLabel bramo;
    private javax.swing.JLabel brrec;
    private javax.swing.JScrollPane brtab;
    private javax.swing.JPanel busmg_tab;
    private javax.swing.JButton canback;
    private javax.swing.JPanel cancellationtab;
    private javax.swing.JPanel canone;
    private javax.swing.JLabel canveri;
    private javax.swing.JPanel cass_tab;
    private javax.swing.JLabel colamo;
    private javax.swing.JTextField fname;
    private javax.swing.JButton gbbox;
    private javax.swing.JComboBox gender;
    private javax.swing.JPanel infotwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel lcantwo;
    private javax.swing.JLabel lday;
    private javax.swing.JTextField lname;
    private javax.swing.JPanel logintab;
    private javax.swing.JLabel lramo;
    private javax.swing.JLabel lrbut;
    private javax.swing.JLabel lrrec;
    private javax.swing.JScrollPane lrtab;
    private javax.swing.JPanel maintab;
    private javax.swing.JComboBox mealpref;
    private javax.swing.JTextField passbox;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField pnrfield;
    private javax.swing.JScrollPane pnrrec;
    private javax.swing.JPanel pnrtab;
    private javax.swing.JTextField pnrveri;
    private javax.swing.JScrollPane prorec;
    private javax.swing.JPanel protab;
    private javax.swing.JButton rb1;
    private javax.swing.JPanel repprotab;
    private javax.swing.JScrollPane reprec;
    private javax.swing.JPanel reptab;
    private javax.swing.JPanel reservationtab;
    private javax.swing.JPanel resone;
    private javax.swing.JTabbedPane rptab;
    private javax.swing.JComboBox seatpref;
    private javax.swing.JComboBox seatzone;
    private javax.swing.JButton selback;
    private javax.swing.JComboBox selclass;
    private javax.swing.JComboBox selsector;
    private javax.swing.JLabel selsub;
    private javax.swing.JComboBox seltrad;
    private javax.swing.JComboBox ssr;
    private javax.swing.JComboBox status;
    private javax.swing.JLabel subinfo;
    private javax.swing.JTextField userbox;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel veribox;
    // End of variables declaration//GEN-END:variables

    private void price() {
        if (selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("First Class")) {
            amo = "400.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Chicago to New-York") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "250.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("First Class")) {
            amo = "430.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Memphis to New-York") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "240.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("First Class")) {
            amo = "410.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "310.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Miami to New-York") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "260.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("First Class")) {
            amo = "450.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "380.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-Orleans to New-York") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("First Class")) {
            amo = "400.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Chicago") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "250.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("First Class")) {
            amo = "430.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Memphis") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "240.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("First Class")) {
            amo = "380.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "310.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Miami") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "260.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("First Class")) {
            amo = "450.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "380.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to New-Orleans") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "330.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("First Class")) {
            amo = "200.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "150.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("New-York to Pittsburgh") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "120.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("First Class")) {
            amo = "200.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("Business Class")) {
            amo = "150.00";
            amofield.setText(amo);
        } else if (selsector.getSelectedItem().equals("Pittsburgh to New-York") && selclass.getSelectedItem().equals("Economy Class")) {
            amo = "100.00";
            amofield.setText(amo);
        } else {
            amo = "Error getting Price!";
            JOptionPane.showMessageDialog(this, amo);
            amofield.setText(amo);
        }
    }

}
